/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rentalTokenOwnershipSol from "./RentalTokenOwnership.sol";
export type { rentalTokenOwnershipSol };
import type * as tokenOwnershipSol from "./TokenOwnership.sol";
export type { tokenOwnershipSol };
