/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as rentalTokenOwnershipSol from "./RentalTokenOwnership.sol";
export * as tokenOwnershipSol from "./TokenOwnership.sol";
