name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3

      - name: Installation
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Run Development Server
        run: |
          nohup npm start > server.log 2>&1 & # start the server and log output
          for i in {1..5}; do
            if curl --fail http://localhost:3000/; then
              echo "Server is live!"
              break
            else
              echo "Waiting for server to start..."
              sleep 5
            fi
          done
          if ! curl --fail http://localhost:3000/; then
            echo "Server failed to start. Logs:"
            cat server.log
            exit 1
          fi |
      
      - name: Run Builds
        run: npm run build


        
